name: Boomerang
packages: 
  RxDataSources: 
    url: https://github.com/RxSwiftCommunity/RxDataSources
    from: "5.0"
  RxSwift: 
    url: https://github.com/ReactiveX/RxSwift
    from: "6.0"
options:
  bundleIdPrefix: it.synesthesia
  createIntermediateGroups: true
  xcodeVersion: "12.3"
  transitivelyLinkDependencies: false
  deploymentTarget:
    iOS: "11.0"
    tvOS: "11.0"
    macOS: "10.15"
    watchOS: "6.0"
targets: 
  Boomerang: 
    type: framework
    platform: [iOS, tvOS, macOS, watchOS]
    sources: "Sources/Core"
    scheme:
      gatherCoverageData: true
      testTargets:
      - BoomerangTests_${platform}
  BoomerangTests:
    type: bundle.unit-test
    platform: [iOS, tvOS, macOS, watchOS]
    sources:
    - "BoomerangTests"
    dependencies:
    - target: "Boomerang_${platform}"
  RxBoomerang:
    type: framework
    platform: [iOS, tvOS, macOS, watchOS]
    sources: "Sources/Rx"
    scheme:
      gatherCoverageData: true
      testTargets:
      - RxBoomerangTests_${platform}
    dependencies:
      - target: Boomerang_${platform}
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: RxDataSources
        product: RxDataSources
      - package: RxDataSources
        product: Differentiator
  RxBoomerangTests:
    type: bundle.unit-test
    platform: [iOS, tvOS, macOS, watchOS]
    sources:
    - "RxBoomerangTests"
    dependencies:
    - target: "RxBoomerang_${platform}"
  Demo:
    type: application
    platform: [iOS]
    sources: "Demo"
    scheme:
      gatherCoverageData: true
    dependencies:
      - target: Boomerang_${platform}
      - target: RxBoomerang_${platform}
        
